### ISSUE TITLE
[question] is it ok to send webhook when server raises Internal Error on login?

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Server#142] opened 2023-01-04 20:12 UTC

**Comment by MikeDev101** [comment] 2023-01-24 16:19
If the server raises an internal error when logging in, you likely shouldn't be sending further requests without diagnosing the reason behind the error. Providing the error message would be helpful, and the steps to reproduce the issue.

**Comment by showierdata9978** [comment] 2023-01-24 18:12
> If the server raises an internal error when logging in, you likely shouldn't be sending further requests without diagnosing the reason behind the error. Providing the error message would be helpful, and the steps to reproduce the issue.

Error reason is sent, as it's a cs fix for a cl3  bug

**Comment by showierdata9978** [comment] 2023-01-24 18:13
It's the ghost user bug, alerting that there is a goast user

**Comment by MikeDev101** [comment] 2023-01-24 23:05
If it's a bug with CL3, then this is a zero-priority issue. This will be fixed with the CL4 port.

**Comment by showierdata9978** [comment] 2023-01-24 23:12
> If it's a bug with CL3, then this is a zero-priority issue. This will be fixed with the CL4 port.

this is a question lol, IK itl get fixed in cl4 but if it does happen that user is basically shadow banned

**Comment by MikeDev101** [comment] 2023-02-07 20:03
Closing since gone stale / won't fix legacy code.

**Closed by MikeDev101** 2023-02-07 20:03 UTC
Labels: bug, question, wontfix, CloudLink related
